version: '3.8'

services:
  bookservice:
    build: 
      context: docker-compose
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/book_service
      - SPRING_DATASOURCE_USERNAME=book_service
      - SPRING_DATASOURCE_PASSWORD=book_service

  postgres:
    image: postgres:17.2
    container_name: book_service
    environment:
      - POSTGRES_USER=book_service
      - POSTGRES_PASSWORD=book_service
      - POSTGRES_DB=book_service
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
